"""Role-family briefs: generated once per role family, cached, reused forever.

A role brief is a compact, company-agnostic summary of what a role family (MLE,
Forward Deployed Engineer, AI Engineer, ...) usually is and screens for. It is
generated by ONE brain call the first time a family is seen (seeded with the job's
title + JD as the example), stored under data/role_cache/<slug>.json, and injected
into every subsequent tailor call for that family as extra context. The JD always
overrides the brief where they disagree; the brief supplies the role-family prior
(including soft skills, but only when the generating model judged they genuinely
matter for the family - nothing is hardcoded here).

Files are plain JSON ({role_name, summary, typical_keywords}) and hand-editable:
a user's edits persist because generation only runs on a cache MISS.
"""

from __future__ import annotations

import json
import re

from .. import config, prompts

CACHE_DIR = config.DATA_DIR / "role_cache"

BRIEF_SCHEMA = {
    "type": "object",
    "properties": {
        "role_name": {"type": "string"},
        "summary": {"type": "string"},
        "typical_keywords": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["role_name", "summary", "typical_keywords"],
    "additionalProperties": False,
}

# Title tokens that name a level/track/cohort, not the role family itself.
_NOISE = {
    "senior", "sr", "junior", "jr", "staff", "principal", "lead", "associate",
    "i", "ii", "iii", "iv", "v", "1", "2", "3", "4", "5",
    "new", "grad", "graduate", "intern", "internship", "entry", "level",
    "early", "career", "university", "campus", "phd", "us", "usa", "remote",
    "contract", "fulltime", "copy",
}


def normalize(title: str) -> str:
    """Job title -> role-family slug. Drops the company-specific tail (after the
    first separator), parentheticals, and level/cohort noise words, so
    "Senior Machine Learning Engineer II - Search Ads (Remote)" and
    "Machine Learning Engineer New Grad" both map to machine-learning-engineer."""
    t = (title or "").strip()
    # Keep the segment that actually NAMES a role: "Compliance - Applied AI/ML Data
    # Scientist - Associate" must resolve to the data-scientist segment, not the
    # department prefix. Fall back to the first segment when none names a role.
    segs = re.split(r"\s+[-–—,|:]\s+", t)
    ROLE_WORDS = re.compile(r"engineer|scientist|developer|manager|analyst|designer|"
                            r"architect|researcher|marketer|specialist|consultant|lead",
                            re.I)
    t = next((s for s in segs if ROLE_WORDS.search(s)), segs[0])
    t = re.sub(r"\([^)]*\)", " ", t)                # drop parentheticals
    t = re.sub(r"[^A-Za-z0-9 ]", " ", t).lower()
    toks = [w for w in t.split() if w not in _NOISE]
    return "-".join(toks) or "unknown-role"


def get_brief(role_title: str) -> dict | None:
    """The cached brief for this title's role family, or None."""
    path = CACHE_DIR / f"{normalize(role_title)}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def get_or_create(role_title: str, jd_text: str, brain) -> dict:
    """Cached brief, generating it with ONE brain call on a miss (the call raises
    BrainPending in manual mode - callers already handle that per job). The example
    JD only seeds generalization; nothing company-specific should land in the file."""
    brief = get_brief(role_title)
    if brief:
        return brief
    user = (f"ROLE TITLE: {role_title.strip()}\n\n"
            f"EXAMPLE JOB DESCRIPTION (one instance of this family; generalize, do "
            f"not copy company specifics):\n{(jd_text or '').strip()[:6000]}")
    brief = brain.structured("role", system=prompts.ROLE_BRIEF_SYSTEM, user=user,
                             schema=BRIEF_SCHEMA)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = CACHE_DIR / f"{normalize(role_title)}.json"
    path.write_text(json.dumps(brief, indent=2))
    return brief


def as_context(brief: dict) -> str:
    """The brief rendered as the ROLE FAMILY CONTEXT block for the tailor prompt."""
    kw = ", ".join(brief.get("typical_keywords") or [])
    return (f"ROLE FAMILY CONTEXT (cached, company-agnostic; THIS JD overrides it "
            f"wherever they disagree):\nRole family: {brief.get('role_name', '')}\n"
            f"{brief.get('summary', '')}\n"
            + (f"Typical keywords: {kw}" if kw else ""))
